MAX_DROPDOWNS = 5
DEFAULT_PERIOD_TYPE = 'ytd'
DEFAULT_START_QUARTER = '2022Q1'
DEFAULT_END_QUARTER = '2024Q3'
DEFAULT_REPORTING_FORM = '0420162'
TOP_N_LIST = [999]
DEFAULT_CHECKED_LINES = ['осаго']
DEFAULT_METRICS = ['direct_premiums']
DEFAULT_INSURER = ['top-10']


DEFAULT_METRICS_158 = ['total_premiums']

DEFAULT_NUMBER_OF_PERIODS = 2
DEFAULT_BUSINESS_TYPE = ['direct']
DEFAULT_SHOW_MARKET_SHARE = []
DEFAULT_SHOW_CHANGES= ['show']
DEFAULT_SPLIT_MODE='line'